name: douyin_downloader
description: Flutter app to download Douyin videos.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  video_player: ^2.7.0
  gallery_saver_plus: ^3.2.4
  cached_network_image: ^3.2.3
  share_plus: ^11.0.0
  flutter_riverpod: ^2.3.6
  dio: ^5.3.2
  open_file: ^3.3.2
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/